### PR TITLE
Text Update: camelCase to snake_case

### PR DESCRIPTION
**Pull request by Dan-Nolan**
### - What I did

Changed a variable name. Noticed all the other variables are snake_cased while this one was camelCased.

### - How I did it

With my keyboard :)

### - How to verify it

Take a look!

### - Description for the changelog

No Change

### - Cute Animal Picture

image

### CODE REVIEW

**Comment by Dan-Nolan** [comment]
Actually, I noticed a couple other places in the Vyper by Example section where camelCase is used. Should we update these as well, or is there a reason why camelCase might be used for state variables?

**Comment by fubuloubu** [comment]
So, mixedCase (CamelCase uppercases the first letter always I think) is used because we need to ensure compatibility with standards that Solidity has already set, being the first language out of the gate and thus ahead on standards.

The way solidity works under the hood (and thus **all** Ethereum smart contracts by convention) is that the first 4 bytes of the call data, when you make a call to an address, are loaded with a slice of the keccak hash of the function signature. So, a function that has signature `myFun(a: address, b: bytes32) -> uint256: ...` has a compressed signature (removing spaces and arg names) of `myFun(address,bytes32)` (the return type is not included in this signature), which gives a hash of `0x160f22da...` that is used to identify which function you are trying to call when you call a contract at address `X`.

So, what this means is that if we want to be compliant with things like ERC-20, our function names (such as `transferFrom`) really matter what case they are in, since snake case would give you a totally different hash and thus not be compliant with the spec. Same goes with state variables, since we sometimes use the `public` keyword to generate a getter, so functions like `totalySupply` must also have matching case in order to generate the same getter.

Now, that does not mean all variables have to have the same casing, but if we've come this far we might as well adopt it all to make it consistent. It is therefore a recommendation of the style guide (and a requirement for ERC compatibility) to use mixedCase for **everything** even though it's not the same as Python. The context switching between the two is difficult, but helps our users disambiguate between the two syntaxes a little quicker hopefully.

---

See [here](https://solidity.readthedocs.io/en/develop/abi-spec.html) for more information.

NOTE: Unfortunately, the ABI spec is still maintained alongside the Solidity documentation, which means it basically maintains the ABI spec. We should do something about that! Compilers Ring FTW!

**Comment by fubuloubu** [comment]
All that being said, I'm going to reject this PR. Would appreciate it if you wanted to PR this information into our docs in the appropriate place if it is not clear. We have internalized this information, but it is always great to have outside perspectives point holes in our documentation so more people know what is going on! Thanks!

**Comment by Dan-Nolan** [comment]
Good to know, thanks for the background information! 

Just now seeing the discussion in #905 and #925, which has been illuminating as well.

**Pull request closed without merging**
