### PR TITLE
Renamed signed256 to int256

### PR DESCRIPTION
**Pull request by BenKaufman10**
Renamed signed256 to int256. Issue #720 

### - How I did it

Renamed signed256 to int256 in the following:
base_types
parse_return
canonicalize_type

### - Description for the changelog

Renamed signed256 to int256.

Please note: This is non-backward compatible. (Added a changelog warning)

### - Cute Animal Picture

image

### CODE REVIEW

**Comment by fubuloubu** [comment]
You could probably merge that into one commit

**Comment by BenKaufman10** [comment]
Yes I believe I can, just not sure how to 😓I am still a github novice...
Will try to do so.

**Comment by fubuloubu** [comment]
You could've kept the issue open, just need to use git on your computer to squash all the commits together

**Comment by BenKaufman10** [comment]
I tried but something didn't work there. Will retry tomorrow.

**Comment by fubuloubu** [comment]
Another strategy I do is save the diff (to master) in a patch, reset the branch to master, the apply the patch.

If you force commit, GitHub will update. GitHub doesn't track merged well, as I'm sure you're finding out now lol

**Comment by BenKaufman10** [comment]
Lol I noticed that. I finally managed to fix it all (at least it was a good git practice :) ).
Thanks for the help

**Pull request merged**
