### PR TITLE
Change name of num types

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did
Implements VIP #674 .
Renames num to int128.
Renames num256 to uint256.

### - How I did it
Ctrl+Shift+F

### - How to verify it
Write a few int128 programs and check the tests.

### - Description for the changelog
Renames num to int128.
Renames num256 to uint256.

### CODE REVIEW

**Comment by fubuloubu** [comment]
Well, that looked like fun! (107 files changed)

LGTM. Did you check the `examples/` folder?

**Comment by jacqueswww** [comment]
@fubuloubu yeah crazy! Yes I think I checked there too :smile: 
image

**Comment by DavidKnott** [comment]
@jacqueswww LGTM, merging.

**Comment by marci** [comment]
I suppose documentation should be updated too (example using num type: https://vyper.readthedocs.io/en/latest/vyper-by-example.html#crowdfund).

**Comment by aldoborrero** [comment]
Yup, documentation is not updated.

**Pull request merged**
