### PR TITLE
Add opcodes and opcodes_runtime flags to compiler

### PR DESCRIPTION
**Pull request by iamdefinitelyahuman**
### What I did

 * added `opcodes` and `opcodes_runtime` flags to the compiler

### How I did it

 * added `PUSH`, `SWAP` and `DUP` opcodes to `vyper/opcodes.py`
 * added new method `get_opcodes` to `vyper/compiler.py`
 * added `opcodes` and `opcodes_runtime` to `output_formats_map` in `vyper/compiler.py`
 * modified help string in `bin/vyper`

### How to verify it

`vyper -f opcodes examples/crowdfund.vy`
`vyper -f opcodes_runtime examples/crowdfund.vy`

### Description for the changelog

 * added `opcodes` and `opcodes_runtime` flags to the compiler

### Cute Animal Picture

baby sloth like opcodes

### CODE REVIEW

**Comment by jacqueswww** [comment]
@fubuloubu doc tests are great for a quick test suite, but in general I think it just adds too much clutter on a code base - especially since we have a very extensive test suite already.

**Comment by fubuloubu** [comment]
Doctests are nice because they keep the docs up to date

**Comment by iamdefinitelyahuman** [comment]
> LGTM, just fix the linting errors ;)

oops!

**Comment by killersqueegie** [comment]
What's the difference between `opcodes` and `opcodes_runtime`?

**Comment by iamdefinitelyahuman** [comment]
* `opcodes` is generated from the bytecode used to deploy the contract
* `opcodes_runtime` is from the final deployed bytecode that is stored on-chain

If you are familiar with `solc`:

* `opcodes` is equivalent to `evm.bytecode.opcodes`
* `opcodes_runtime` is equivalent to `evm.deployedBytecode.opcodes`

**Pull request merged**
