### PR TITLE
Convert to CircleCI config

### PR DESCRIPTION
**Pull request by pipermerriam**
### What I did

Converted the project to use CircleCI for automated testing.

### Why?

- We've found it to be at least as reliable as travis and potentially more reliable.
- We've found it to be faster than travis.
- The EF has a paid plan so there's more build capacity available.

### Cute Animal Picture

baby-fox-in-den

### CODE REVIEW

**Comment by pipermerriam** [comment]
This shouldn't be merged as-is.  I did not convert the deploy component since it requires a secret value that I don't have.  Assuming we move forward with this,  I'll need to work with whoever has access to that to set it up in circle.

**Comment by pipermerriam** [comment]
FYI, the linter failure exposes that linting was not being run in travis.  It's not clear to me why, but we'll have to get that cleaned up first to move this forward.

**Comment by jacqueswww** [comment]
@pipermerriam have the deploy details, I believe it's for snapcraft ? ;)

**Comment by fubuloubu** [comment]
Should we add python 3.7 support as well?

**Comment by pipermerriam** [comment]
@fubuloubu :+1: I can go ahead and expand the test runs to include that.

**Comment by fubuloubu** [comment]
This is a really big commit. Is there any way we can split out these style changes into another branch? I'm not sure if that's the right way to go, but this is definitely getting to be an onerous PR

**Comment by pipermerriam** [comment]
Lint happy, code sad :frowning: will get whatever functionality changes occured because of this cleaned up tomorrow and then I'll work to divide this into smaller sections so it can be reasonably reviewed and merged in consumable chunks.

**Comment by fubuloubu** [comment]
I have no problem with non-functional changes being in a larger PR as long as you do the curation work of ensuring functional changes are kept separate and smaller (and in a different PR).

We can then merge the CircleCI stuff when you are ready!

**Comment by pipermerriam** [comment]
Alright, waiting for test runs to confirm everything is passing.  This should be zero functionality changes, pure reformatting of code to conform to linting standards.

**Comment by pipermerriam** [comment]
Oh, worth noting this does **not** include the snapcraft deploy.  @jacqueswww is that something you know enough about to push on top of this?

**Comment by pipermerriam** [comment]
I don't know what the policy is for merging things so I'm somewhat deferring to @jacqueswww or someone to give me the :+1:  that this can be merged.

**Comment by jacqueswww** [comment]
I did a priliminary paas through, seems reasonable. Will do one more pass through on Monday and then we can merge.

**Comment by davesque** [comment]
I agree that there's value in getting this on circle CI and in getting things passing flake8 but I really think this needs to be split up into smaller PRs. The reason is that, the more repetitive changes that people have to examine, the more likely they are to miss something. The test suite might catch something like that but it also might not.

**Comment by pipermerriam** [comment]
@davesque On monday I'll split this up into smaller bits so we can review it a single file at a time and we can merge them over the course of next week.

**Comment by davesque** [comment]
@pipermerriam I don't know if you've started work on splitting things up already, but I'd be happy to do that since I tied a bow on the web3 stuff.

**Comment by pipermerriam** [comment]
I have not, go for it.

**Comment by davesque** [comment]
I believe all the changes in this PR have been incorporated by all the separate linting PRs.

**Comment by fubuloubu** [comment]
Can we delete this branch?

**Pull request closed without merging**
