### PR TITLE
change lines included in code examples to match discussion text

### PR DESCRIPTION
**Pull request by sguberman**
### - What I did
The example code sections did not match the discussion text. I made them match. Relates to #579 

### - How I did it
Rather than including specific line numbers, where possible I used the `pyobject` option to match the function being discussed. This way, if the source code file is updated, the docs will follow automatically once rebuilt. I learned about this by reading the Sphinx [docs](http://www.sphinx-doc.org/en/master/markup/code.html#includes) related to showing code examples.

### - How to verify it
Read the docs! Specifically, any of the Vyper By Example sample code in line with the explanatory paragraphs.

### - Description for the changelog
Fix example code shown shown in line with Vyper By Example docs.

### - Cute Animal Picture
A very cute albino Tanuki!
image

### CODE REVIEW

**Comment by fubuloubu** [comment]
Fantastic! Do you know if there is a way to view this on read the docs, or does it need to be done locally to verify?

**Comment by sguberman** [comment]
Good point @fubuloubu that did not occur to me at all, and I should have explained in my "how to verify it" section that I built locally to confirm the correct changes to the documentation. However, your question gave me an idea. I set up my own account at readthedocs and connected it to my fork and this branch, so you should be able to view the changes yourself [here](https://sguberman-vyper.readthedocs.io/en/latest/vyper-by-example.html).

**Comment by fubuloubu** [comment]
Awesome! Looks great!

Is it a bug that so much extra space appears at the end of the full file inclusions? That bothers me lol

**Comment by fubuloubu** [comment]
I remember seeing it before, so I don't think you caused it.

**Comment by sguberman** [comment]
Yeah that bothers me too, and it's what tipped me off to the line spacing being different between the line numbers and the code. I didn't try to fix that at all this time, just wanted to make sure the correct shorter code sections were being shown with the text. A quick fix would be to just turn off line numbering for those full file inclusions, but I thought it would be better to separate the two concerns into different PRs.

You shouldn't be seeing any blank space after the shorter inclusions because I left the line numbers off (as was done in the original).

**Comment by fubuloubu** [comment]
LGTM!

**Pull request merged**
