### PR TITLE
Inject git commit into version

### PR DESCRIPTION
**Pull request by charles-cooper**
### - What I did
Make it so the git commit is displayed with `vyper --version`

### - How I did it
Inject the git commit into setup.py and make bumpversion accept the new format

### - How to verify it
`make && vyper --version`

### CODE REVIEW

**Comment by jacqueswww** [comment]
@fubuloubu @charles-cooper I am not sure if this is what we want?

image

Basically all release version will the commit hash in now?

**Comment by fubuloubu** [comment]
I would like that to be true, so you can pin down what version you're working with. Does it screw with `pip` or version pinning at all?

**Comment by fubuloubu** [comment]
I'm also okay with the package version not containing it, but `vyper --version` returning with the hash

**Comment by charles-cooper** [comment]
I guess publishing to the index server is not supposed to have a 'local version' in it (cf. https://www.python.org/dev/peps/pep-0440/#local-version-identifiers). I think there is a way to bundle the local version as additional metadata but I need to research a bit further.

**Comment by charles-cooper** [comment]
I changed the implementation so it doesn't touch the PKG-INFO version at all but instead stores the git commit in the dist data which is then looked up and appended to the version. However, I'm seeing some weirdness in creating the temp dir with `sdist`, awaiting resolution at https://github.com/pypa/setuptools/issues/1692.

**Comment by charles-cooper** [comment]
@fubuloubu @jacqueswww I am kind of giving up hope that pypa will look into this issue. As a potential workaround, how about writing to a temporary file in the working directory? E.g. `build/GITVER.txt`?

**Comment by fubuloubu** [comment]
I think we can abandon this proposal.

**Comment by fubuloubu** [comment]
@charles-cooper closing this one for now

**Pull request closed without merging**
