### PR TITLE
Update ERC20 tests for new Vyper type annotation requirements, clamp restrictions

### PR DESCRIPTION
**Pull request by pdaian**
### - What I did

Made the Solidity-compatible ERC20 tests pass again.

### - How I did it

Updated the contract and tests when necessary for:
- Function visibility modifier requirements
- Data type annotations
- The restriction described in #653

### - How to verify it

Follow the instructions to run the corresponding tests (`run_tests.py`).

### - Description for the changelog

Update Solidity-compatible ERC20 tests for new Vyper annotation requirements and clamp restrictions.

### - Cute Animal Picture

```
       __
 __   (__`\
(__`\   \\`\
 `\\`\   \\ \
   `\\`\  \\ \
     `\\`\#\\ \#
       \_ ##\_ |##
       (___)(___)##
        (0)  (0)`\##
         |~   ~ , \##
         |      |  \##
         |     /\   \##         __..---'''''-.._.._
         |     | \   `\##  _.--'                _  `.
         Y     |  \    `##'                     \`\  \
        /      |   \                             | `\ \
       /_...___|    \                            |   `\\
      /        `.    |                          /      ##
     |          |    |                         /      ####
     |          |    |                        /       ####
     | () ()    |     \     |          |  _.-'         ##
     `.        .'      `._. |______..| |-'|
       `------'           | | | |    | || |
                          | | | |    | || |
                          | | | |    | || |
                          | | | |    | || |     Joan Stark
                    _____ | | | |____| || |
               jgs /     `` |-`/     ` |` |
                   \________\__\_______\__\
```

### CODE REVIEW

**Comment by fubuloubu** [comment]
Thanks for the updates.

For the tests, can it be py.test instead of unit test?

**Comment by pdaian** [comment]
@fubuloubu can do that but it's a big test suite and may require some work.  Will look at it after a paper deadline I have on Feb 8.

**Comment by fubuloubu** [comment]
No problem, this update looks good to me and I think it should be merged, just would be nice to be fully aligned on our testing suite.

**Comment by jacqueswww** [comment]
@fubuloubu  @pdaian I updated these change into https://github.com/ethereum/vyper/pull/706. Because stuff changed since this PR ;) If you could just do a quick check then I can merge it.

**Comment by jacqueswww** [comment]
Closing, feel free to create another PR if #706 didn't apply above changes correctly. :smile:

**Pull request closed without merging**
