### PR TITLE
Improved built in functions documentation

### PR DESCRIPTION
**Pull request by ben-kaufman**
Improved the documentation for Vyper's built in functions.

### - Cute Animal Picture

image

### CODE REVIEW

**Comment by ben-kaufman** [comment]
I just added documentation for Vyper's "low-level" functions. I still have a few questions in order to be able to finish this documentation. Any help with that will be really appreciated.

Regarding ``raw_call``:
1. What is the outsize?
2. Should I write num_literal in the docs as the argument type or should I say int128?
3. Is the function returns something? If so what?

What is ``raw_log``?

**Comment by jacqueswww** [comment]
`raw_log` like `raw_call` allows you to emit a log statement without specifying the abi type, by just passing it a bunch of arguments.

**Comment by jacqueswww** [comment]
`outsize` is the basically the size of the bytes that get returned from the `CALL` opcode. Basically the maxlen to the bytes output from `rawcall`.

**Comment by jacqueswww** [comment]
I think just say something like "fixed literal value" ;)

**Comment by fubuloubu** [comment]
maybe it can be called `bytes_size` to be more explicit?

**Comment by ben-kaufman** [comment]
Thinking about it, why do we need to specify the variable names in the ``raw_call` function.
I think it would be better to remove it if there's no special reason for that.

**Pull request merged**
