### PR TITLE
Rename python module to Vyper.

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did

Part of #501.

OK here goes :drum: 
Renamed viper module to vyper. This should be merged right after the docs merge.

### - How I did it
n/a

### - How to verify it
I guess if tests pass we are OK ? haha

### - Description for the changelog

Renamed viper to vyper.

### CODE REVIEW

**Comment by jacqueswww** [comment]
@fubuloubu @DavidKnott get's tricky now if you look at CI output, I also created the following PR at pyethereum:  https://github.com/ethereum/pyethereum/pull/854

**Comment by fubuloubu** [comment]
That is quite a chicken and egg problem lol.

I think the best case scenario is that someone for pyethereum adds a new `vyper` option first, releases that to pypi, to which you upgrade the version of pyethereum we use in our package, THEN  allowing us to make the switch under the hood in this PR. After that is complete, cycle back to pyethereum and remove the old `viper` language option, which can be released at your leisure.

Eventually, we should move our tests to a testing framework built as a `py.test` plugin using `eth-tester` with `py-evm` as a backbone, but there is some additional stuff that is needed IMO before we can do this relating to how the compilers are handled, as well as adding some useful features for measuring coverage and profiling gas costs.

**Comment by fubuloubu** [comment]
@DavidKnott needs a `pre beta` tag

**Comment by DavidKnott** [comment]
@jacqueswww Can you rebase this?

**Comment by jacqueswww** [comment]
@DavidKnott done :)

**Comment by fubuloubu** [comment]
Soooo many changes. Thanks for your effort @jacqueswww!

**Comment by jacqueswww** [comment]
Sure thing! Glad to see the rename is almost done 😁

**Pull request merged**
