### PR TITLE
WIP: Fix tuple return, from public call to self.

### LINKED ISSUE #1551: Nonsense struct output with inline returns
### Version Information

* vyper Version (output of `vyper --version`): 0.1.0b10
* OS: osx
* Python Version (output of `python --version`): Python 3.7.2
* Environment (output of `pip freeze`): 
```
eth-tester==0.1.0b39
py-evm==0.2.0a42
pytest==5.0.1
vyper==0.1.0b10
web3==5.0.0b2
```

### What's your issue about?

When `@public` functions which return structs are returned inline from other `@public` functions, the output is nonsense values.

In the following code, `wrap_get_my_struct_WORKING` returns the correct data, whereas `wrap_get_my_struct_BROKEN` returns nonsense.

```python
struct MyStruct:
    e1: decimal
    e2: timestamp


# @dev Construct a MyStruct.
@public
@constant
def get_my_struct(_e1: decimal, _e2: timestamp) -> MyStruct:
    return MyStruct({e1: _e1, e2: _e2})
 

# @dev Wrap self.get_my_struct.
@public
@constant
def wrap_get_my_struct_WORKING(_e1: decimal) -> MyStruct:
    testing: MyStruct = self.get_my_struct(_e1, block.timestamp)
    return testing

# @dev Wrap self.get_my_struct.
@public
@constant
def wrap_get_my_struct_BROKEN(_e1: decimal) -> MyStruct:
    return self.get_my_struct(_e1, block.timestamp)
```

### PR DESCRIPTION
**Pull request by jacqueswww**
### What I did
Fixes #1551.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by davesque** [comment]
@jacqueswww I figured I'd give this a quick review but I'm having some trouble understanding why that one-liner fixes the issue.  Wouldn't `sub` in this context be the LLL for the public self-call?  So it would look something like the code generated by [`call_self_public`](https://github.com/ethereum/vyper/blob/a3a3cf8f84c31e027b2fcbe59fb5f4269716104a/vyper/parser/self_call.py#L283-L286)?  As much as I can tell, `call` ops just push a success value onto the stack.  I think the `assert` directive consumes this success value since with the `JUMPI` op that it generates.  So how would we end up with a relevant memory position on the stack?

**Comment by jacqueswww** [comment]
Well if you look at the IR, sub returns the mempos of where the result is stored. That why I made it `mempos = sub` (instead of just moving sub) if you check further you would see that asserting the call was also left out.

**Comment by davesque** [comment]
@jacqueswww Yeah, I see now.  I was missing the fact that the output size is greater than zero so the call gets wrapped in a `seq` with the position of the returned value.  Was just trying to understand so I can follow what's being done here.

**Comment by davesque** [comment]
@jacqueswww Okay, yeah now I see why your fix worked.  Correct me if I'm wrong, but the previous implementation of `gen_tuple_return` was just skipping over the call and never making it and directly outputting the memory address where the return data would have gone.

So yeah, LGTM.

**Comment by davesque** [comment]
@jacqueswww It seems like the name and location of the test file doesn't match what's being tested.  We're not really testing interaction with an external contract and the test file name `test_self_call.py` seems like it should maybe be something like `test_self_call_struct.py`.  What do you think?

Also, I'm curious what more you wanted to add to this PR.  Were the things you wanted to add critical to the fix or just peripheral?  My concern is that the issue seems a bit high priority and maybe should merge in what's here and then iterate.

**Comment by charles-cooper** [comment]
There's a commented out test in one of the test_struct files we should uncomment

**Comment by jacqueswww** [comment]
We can merge it, was just a change to detect the sel call easier.

**Comment by jacqueswww** [comment]
@charlescooper turns out I "fixed" in support for it.

**Comment by davesque** [comment]
@jacqueswww Would it be possible to rename the test file like I mentioned?

**Comment by jacqueswww** [comment]
Yeah no problem, will do - then merge.

**Pull request merged**
