### PR TITLE
Use NatSpec [WIP]

### LINKED ISSUE #898: Adopt NatSpec
Adopt NatSpec for function definitions.

NatSpec is documented here https://github.com/ethereum/wiki/wiki/NatSpec-Determination and it is perfectly applicable to vyper.

The a of vyper is: "Vyper code should be maximally human-readable."

Presently it is difficult to grok functions because you may need to read all the code to see how the parameter is used. With natspec you can document all function parameters.

If NacSpec is adopted, it should be added for all functions in https://github.com/ethereum/vyper/tree/master/examples

### PR DESCRIPTION
**Pull request by fulldecent**
# Work plan

- [x] Add NatSpec to documentation, somewhere in https://vyper.readthedocs.io/en/latest/vyper-by-example.html?highlight=sender
- [ ] Identify all examples where documentation is appropriate
- [ ] Add NatSpec to those places
- [ ] Identify external stakeholders (like https://vyper.online) and ask them to update in step

Fixes #898

### CODE REVIEW

**Comment by fulldecent** [comment]
@jacqueswww 

The PR right now uses one format for documentation. Can you please advise if a different format would be more Pythony?

CURRENTLY IN PR:

```py
# @author Bob Clampett
# @notice Determine if Bugs will accept `food` to eat
# @dev Compares the entire string and does not rely on a hash
# @param food The name of a food to evaluate (in English)
# @return true if Bugs will eat it, false otherwise
@public
@payable
def doesEat(food: string):
```

SHOULD I USE THIS?

```py
@public
@payable
def doesEat(food: string):
  """
  : @author Bob Clampett
  : @notice Determine if Bugs will accept `food` to eat
  : @dev Compares the entire string and does not rely on a hash
  : @param food The name of a food to evaluate (in English)
  : @return true if Bugs will eat it, false otherwise
  """
```

**Comment by jacqueswww** [comment]
Wow! This excellent.

I am leaning towards using the docblocks (case 2).

I will add this to the bi-weekly call agenda, to see what others think.

**Comment by fubuloubu** [comment]
Doc blocks/doc strings :+1:

Why is the colon necessary though?

**Comment by fulldecent** [comment]
Version 3

```py
@public
@payable
def doesEat(food: string):
  """
  @author Bob Clampett
  @notice Determine if Bugs will accept `food` to eat
  @dev Compares the entire string and does not rely on a hash
  @param food The name of a food to evaluate (in English)
  @return true if Bugs will eat it, false otherwise
  """
```

References https://www.python.org/dev/peps/pep-0257/

**Comment by jacqueswww** [comment]
Looks good to me.

**Comment by maurelian** [comment]
```
# What about events?
Transfer: event({_from: indexed(address), _to: indexed(address), _tokenId:indexed(uint256)})
```

**Comment by jacqueswww** [comment]
For events one would have to use comment block... which makes it a bit inconsistent with using doc blocks.

**Comment by maurelian** [comment]
Python must have dealt with this in some similar situation.

**Comment by fulldecent** [comment]
At present, NatSpec does not apply to events.

https://github.com/ethereum/wiki/wiki/Ethereum-Natural-Specification-Format

**Comment by fulldecent** [comment]
Regarding the contract-wide NatSpec, we had discussed adding it to the top of the Vyper file. 

So for example here https://github.com/ethereum/vyper/blob/master/examples/market_maker/on_chain_market_maker.vy it would go immediately at the top and have one empty line following.

Are there situations when the contract-wide NatSpec would not be the immediately first line of the file? Can we please enumerate them all.

**Comment by fubuloubu** [comment]
@fulldecent I think where the compiler version goes is important. I usually add near the top, above my docs for the file. Perhaps we can just enforce "one contract-wide docstring" and suggest you place it near the top per the style guide?

**Comment by fubuloubu** [comment]
Also, Natspec should totally have events.

**Comment by fulldecent** [comment]
Add NatSpec to events -> https://github.com/ethereum/wiki/issues/605

**Comment by fulldecent** [comment]
Version 3 is implemented in the PR. I am recommending to merge this for now.

There are additional work plan items here, but those can be moved to an issue that outlives this PR, if desired.

**Comment by jacqueswww** [comment]
@fulldecent I think just fix the flake8 errors and we can merge.
```
vyper/parser/self_call.py:175:9: W504 line break after binary operator
vyper/parser/self_call.py:176:9: W504 line break after binary operator
vyper/parser/self_call.py:177:9: W504 line break after binary operator
vyper/parser/expr.py:121:47: W504 line break after binary operator
vyper/parser/parser.py:406:13: W504 line break after binary operator
vyper/parser/parser.py:407:13: W504 line break after binary operator
vyper/parser/stmt.py:480:21: W504 line break after binary operator
vyper/parser/stmt.py:481:21: W504 line break after binary operator
vyper/parser/stmt.py:576:21: W504 line break after binary operator
vyper/parser/stmt.py:577:21: W504 line break after binary operator
vyper/parser/stmt.py:578:21: W504 line break after binary operator`
```

**Pull request merged**
