### PR TITLE
Adds support deleting for nested map keys.

### LINKED ISSUE #715: Fix deleting a value from a map.
### What's your issue about?

It seems that `del` keyword doesn't work for a map.
```
E           vyper.exceptions.StructureException: line 14: Unsupported statement type
E               del self.big_storage[key]
E           ----^
```

Example test case:
```
def test_map_delete(get_contract):
    code = """
big_storage: bytes32[bytes32]

@public
def set(key: bytes32, value: bytes32):
    self.big_storage[key] = value

@public
def get(key: bytes32) -> bytes32:
    return self.big_storage[key]

@public
def delete(key: bytes32):
    del self.big_storage[key]
    """

    c = get_contract(code)

    assert c.get("test") == b""
    assert c.set("test", "value")
    assert c.get("test") == b"value"
    c.delete("test")
    assert c.get("test") == b""
```

This will be done

### How can it be fixed?

Fixed by using `SSTORE 0x0`on the sha32'ed key value.

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did

Fixes #715.

### - How I did it

Added parse_delete to handle the specific case.

### - How to verify it

Check tests `del self.big_map["test"]` should now work.

### - Description for the changelog
Add deleting support for a map.

### CODE REVIEW

**Comment by fubuloubu** [comment]
Can you `del` a struct?

**Comment by jacqueswww** [comment]
It can, but it seems to do it incorrectly. Will have a look.

**Comment by Thrasymachus01** [comment]
Any update on this? I am getting an error when trying to use this keyword:
`vyper.exceptions.SyntaxException: Deleting is not supported`

**Comment by fubuloubu** [comment]
@Thrasymachus01 this was removed in v0.2.0

To "delete" a value in a mapping, use `self.mapping[key] = empty(ValueType)` or similar

**Pull request merged**
