### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by amitkumarj441**
Signed-off-by: Amit Kumar Jaiswal <amitkumarj441@gmail.com>

### - What I did
         Added coincurve

### CODE REVIEW

**Comment by DavidKnott** [comment]
What does `coincurve` have to do with the docs?

**Comment by amitkumarj441** [comment]
I added because we have `libgmp-dev` package under `coincurve` and I just figured out one thing here to add which is travis config for coverall.

**Comment by DavidKnott** [comment]
Creating a `requirements-dev.txt` file makes sense to me, but `requirements-docs.txt` is purely for dependencies that have to do with the documentation.  Could you explain this PR a bit more?

**Comment by amitkumarj441** [comment]
Okay, yes you're right. But I guess `requirements-docs.txt` is going to help when we actually configure travis with `pip install -r requirements-docs.txt` in #420 .

**Comment by jacqueswww** [comment]
@amitkumarj441 not sure we need this anymore, can I close it?

**Comment by jacqueswww** [comment]
Closing as it seems all our CI is still working fine.

**Pull request closed without merging**
