### PR TITLE
Fix convert units

### LINKED ISSUE #865: Convert units should carry
### What's your issue about?

As @djrtwo found.

`convert` should preserve the unit that have been set, currently it doesn't:

```
b: uint256(meter) = 1234
a: int128 = convert(b, "int128") # should error
a: int128(meter) = convert(b, "int128") # should work
```

### How can it be fixed?

Fill this in if you know how to fix it.

### PR DESCRIPTION
**Pull request by jacqueswww**
### - What I did
Fixes #865 .

### CODE REVIEW

**Comment by djrtwo** [comment]
looks good to me

**Comment by djrtwo** [comment]
Shouldn't `int128` -> `decimal` also keep unit? Should add test.

I guess any `convert` we support should keep units, no?

**Comment by jacqueswww** [comment]
@djrtwo `int128` -> `decimal` already does so. But adding a test can not hurt :smile:

**Comment by djrtwo** [comment]
I ❤️ Tests.

**Pull request merged**
