### PR TITLE
Fixes/updates in vyper.utils

### PR DESCRIPTION
**Pull request by davesque**
### What I did

Fixed problem mentioned in issue #1364 .  Updated reserved words list and did some other miscellaneous cleanup.

### How to verify it

Run the tests.

### Description for the changelog

* The keywords `struct` and `msg` were incorrectly being allowed as variable names.  Those keywords are now properly treated as reserved words.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by davesque** [comment]
@jacqueswww I wonder if it really matters that words like this can be used as variable names.  I wonder what some real world examples are of how this would lead to potential security problems or whatever.

**Comment by fubuloubu** [comment]
```python
msg_sender: address = msg.sender  # Weird, but okay I guess

... # Bunch of stuff

transfer(msg_sender, self.balance)  # Could be easy to miss
```

**Comment by davesque** [comment]
@fubuloubu I'm not following. Can you elaborate?

**Comment by davesque** [comment]
@fubuloubu Ahh, I get it now.  That's a good example I guess.

**Comment by jacqueswww** [comment]
@davesque It's basically to avoid ambiguity. You could make a struct with an address called `msg` and the actual address is someting else.

**Comment by davesque** [comment]
@jacqueswww Yeah, I guess in the context of smart contracts, the stakes are higher.  I was thinking that Python allows name shadowing in a lot of cases, but it's a different language with different goals.

**Comment by jacqueswww** [comment]
Merging, all good - and got 2 thumbsup :)

**Comment by jacqueswww** [comment]
@davesque yes exactly. Good example is we also have `blockscopes` in vyper which prohibits shadowing:

```python
for i in range(1, 100):
     ...
# <i is inaccessible here>
```

**Pull request merged**
