### PR TITLE
Add python37 to circle CI

### PR DESCRIPTION
**Pull request by davesque**
### What I did

Added Python 3.7 to Circle CI.

### How I did it

Modified `tox.ini` and `.circleci/config.yml`.

### How to verify it

Run tests.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by fubuloubu** [comment]
Change the build tag from Travis to Circle in README

**Comment by jacqueswww** [comment]
Looks good, did we figure out why this branch is triggering Travis?

**Comment by davesque** [comment]
@jacqueswww No clue.  There don't seem to be any changes I made that would have caused that.  I tried briefly to see if I could delete the Travis project or something but couldn't find a way to do that.  If it keeps happening, I'll dig a bit harder to see if I can find a way to do that.

**Comment by davesque** [comment]
@jacqueswww @fubuloubu Actually, after getting admin access to the vyper github repo, I saw there was still a webhook active for travis CI.  I deleted it.  I think that should fix the issue.

**Pull request merged**
