### PR TITLE
Add Circle CI config and lint whitelist

### PR DESCRIPTION
**Pull request by davesque**
### What I did

Cherry picked and modified Piper's Circle CI config from PR #1262 .  Added all files with linting errors to an explicit whitelist.  It seems like a good strategy here is to merge this PR first, then create a series of subsequent PRs that address linting errors in individual files or groups of files.  Those PRs would fix the errors and also remove the files from the whitelist.  This should also allow linting PRs to be independent of each other.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by jacqueswww** [comment]
@davesque just check your setup.py I just merge pytest-xdist branch.

**Comment by jacqueswww** [comment]
Curios te see how much faster this runs on CircleCI ;)

**Comment by davesque** [comment]
@jacqueswww We'll see.  I'm not sure if the testing environment in a typical circle CI env gives access to more than one CPU.

**Comment by davesque** [comment]
@jacqueswww Well I'll be damned.  That was pretty speedy.

**Comment by jacqueswww** [comment]
Neat! :-)

**Comment by davesque** [comment]
@jacqueswww 
Before:
screen shot 2019-02-26 at 5 22 41 pm

After:
screen shot 2019-02-26 at 5 22 49 pm

**Comment by jacqueswww** [comment]
Very cool, travis is still slow hehe.

**Comment by jacqueswww** [comment]
Ok great, let's do this.

**Pull request merged**
