### PR TITLE
WIP: Setup doctest

### PR DESCRIPTION
**Pull request by siromivel**
### What I did
Added doctests to keep us on top of updating docs

### How I did it
Configured Sphinx to run doctests

### How to verify it
`make -C docs doctest`

### Description for the changelog
Added doctests to the project

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by siromivel** [comment]
I configured Sphinx to run doctests tonight; I'll add some actual tests in tomorrow and move this out of the `WIP` state.

**Comment by fubuloubu** [comment]
@siromivel Any updates on this one? Would be a great update for us to have!

**Comment by siromivel** [comment]
Sorry I never got back to this - wasn't hard to get doctest up and running but I got blocked as I was unable to figure out a reasonable way to execute Vyper in the context of doctests. I'm going to close this as it looks like someone else has started working on the issue and I likely won't have much time for it until August!

**Comment by fubuloubu** [comment]
No worries, thanks for getting it started!

**Pull request closed without merging**
