### PR TITLE
Added clearer tests for string comparison using `keccak256`

### PR DESCRIPTION
**Pull request by jakerockland**
### What I did

Made more explicit the testing of strings longer than 32 bytes

### How I did it

Updated the tests in `types/test_string.py`

### How to verify it

`make test` or `pytest -k types/test_string.py`

### Description for the changelog

Made more explicit the testing of strings longer than 32 bytes

### Cute Animal Picture

image

### CODE REVIEW

**Comment by jakerockland** [comment]
@jacqueswww so I added some additional tests per [our conversation](https://github.com/ethereum/vyper/pull/1507#discussion_r299495005) in #1507, and it _does_ seem to me (unless _I'm_ really tripping here) that string comparisons are working as expected, including those of strings with length greater than 32.

I still don't fully understand _why_ this is the case, as there is a decently sized knowledge gap on my end in understanding the LLL generated for the `keccak256` implementation and would super appreciate if someone could help explain that a bit to me 😅 

Relatedly (or alternatively) is there a good reference for reading up on the LLL? It is very Lisp-y, which is nice in helping my understanding generally, but would be nice to have a reference when trying to make sense of more nuanced pieces like this `keccak256` stuff.

@fubuloubu @charles-cooper @davesque pinging you guys here if you might be able to help here at all. 🙏

**Comment by charles-cooper** [comment]
@jakerockland the layout of a bytestring in memory is
```
| 0   | 32 .. (len - 32) |
| len | data             |
```
The `sha3` LLL macro is called like `(sha3 location len)`. So, given that the bytearray starts at `sub`, `sha3` is called like `(sha3 (add sub 32) (mload sub))`.

**Comment by jakerockland** [comment]
@charles-cooper god that makes so much sense 🙏 thank you for that. 

Was there a way I could have readily looked that up somewhere? 😅

**Comment by charles-cooper** [comment]
@jakerockland not really :joy: it might be nice to document the layout of variables in vyper, right now AFAIK the only way is to read the codebase (sections that come to mind are those on array copy, calling convention, literal parsing) and kind of deduce how they work.

**Comment by jakerockland** [comment]
@charles-cooper 😂😭yeah haha that's what I worried—thank you for helping me understand this one though!

**Comment by davesque** [comment]
@charles-cooper @jakerockland If the `bytes32` type uses the same encoding as the Solidity ABI, then it will *not* be prefixed by a length.  That only happens for the dynamic-length `bytes` ABI type.  Does Vyper assume they're all the same?  If so, that could lead to a bug.

**Comment by davesque** [comment]
@jakerockland Recently, I've toyed with the idea of rewriting the LLL compilation layer to improve readability and also to add informative docstrings.  It could also be good to add a documentation article describing the LLL compilation layer.  That could help contributors a lot.  I'll confess that I was also searching for a good description of LLL for a long time and only finally began to grasp it recently when I bit the bullet and just read the code.  It's rather problematic that our IR (the language used to actually implement features in Vyper) is difficult to understand and not documented at all across the broader ecosystem.

**Comment by jakerockland** [comment]
@davesque so the above convo/string comparisson via `keccak256` hashing only applies to byte arrays, not to the `bytes32` type, as there is already special handling for hashing the `bytes32` type differently (from `vyper/parser/keccak256_helper.py`:

```python
    # Can hash bytes32 objects
    if is_base_type(sub.typ, 'bytes32'):
        return LLLnode.from_list(
            [
                'seq',
                ['mstore', MemoryPositions.FREE_VAR_SPACE, sub],
                ['sha3', MemoryPositions.FREE_VAR_SPACE, 32]
            ],
            typ=BaseType('bytes32'),
            pos=getpos(expr),
        )
```

**Comment by davesque** [comment]
@jakerockland Ahh, thanks for the clarification there.

@charles-cooper @jakerockland Not sure if this is relevant to the discussion, but I thought I'd mention that there's a bit more nuance to the dynamic-length byte string encoding.  As was mentioned, the first 32-byte word is the number of bytes encoded as a `uint256`.  Following the length prefix is the minimum number of 32-byte words necessary to represent all the bytes in the string followed by as many zero-bytes as are necessary to pad the entire encoding to a whole number of 32-byte words.

Not sure if that has any bearing on the discussion but just wanted to make sure things were totally clear there.

**Comment by jakerockland** [comment]
@davesque yeah my understanding of the LLL has also just been a modge-podge of my previous experience with compilers/assembly + Lisps and then reading through the code and piecing together a rough understanding of the Ethereum LLL. Building out an abstraction layer like that would be wonderful 🥇

**Comment by jakerockland** [comment]
@davesque @charles-cooper I don't _think_ that above additional note/nuance has much bearing as to the current `keccack256` implementation / how it is being used for string/byte array comparisons, but it is definitely very helpful additional context for my mental model 🙏 😄

**Comment by davesque** [comment]
@charles-cooper Ahh, yep.  I read over things a bit more carefully and if that LLL is only ever generated for dynamic-length byte strings then it should be fine.  The trailing zero-padding bytes won't be included in the sha3 input which is correct.

@charles-cooper already touched on this, but to give an alternative explanation: The `(add sub 32)` part is saying that the input to sha3 should begin 32 bytes ahead of the beginning of the string's encoding in memory which omits the length prefix word and only includes the data section.  The `(mload sub)` portions is saying that the number of bytes to send to sha3 is determined by loading the word at location `sub` (the length prefix word) onto the stack as an argument to the sha3 op.

**Comment by jacqueswww** [comment]
@jakerockland I think these 2 test cases are missing:

Comparison between memory (created variable) and storage.
Comparison between memory (passed variable) and storage.

**Comment by jakerockland** [comment]
@jacqueswww just pushed another commit that should handle those cases 👍

**Comment by jacqueswww** [comment]
Thanks! :)

**Pull request merged**
