### PR TITLE
Add vyper-json CLI tool

### LINKED ISSUE #1520: VIP: vyper-json
## Simple Summary

Vyper should provide an interface for non-python-based tools to use.

## Abstract

This VIP proposes the addition of another CLI tool: `vyper-json`. This tool will compile contracts, generating a structured JSON output containing everything needed to integrate Vyper, including errors.

## Motivation

See #1492 

## Specification

This section describes the input and output interfaces of `vyper-json`.

### Input description

`vyper-json` doesn't need any special input apart from a list of files to compile. 

An example execution could be `vyper-json path/to/contract1.vy path/to/other.vy`

#### Output description

`vyper-json` outputs a single JSON object with one key of type `PATH` per input 
file, associated with an object of type `OUTPUT`.

`PATH` values should be absolute paths. If symlinks are present, they should not
be resolved, keeping the path closer to the user's input.

`OUTPUT` values are objects with the following properties:
  * `files`: An array of `PATH` values containing all the source files used to compile this contract. This is useful to implement things like cache, watchers, etc.
  * `errors`: An array of `ERROR` objects. One per each fatal compilation error. This array must be empty if the compilation succeeded.
  * `warnings`: An array of `ERROR` objects. One per each compilation warning. This array must be empty if no warning is emitted.
  * `output`: An object containing `bytecode`, `bytecode_runtime`, `abi`, `source_map`, `method_identifiers` as returned by `vyper` when format `combined_json` is used. This value should be `null` if the compilation failed.

`ERROR` objects must contain the following properties:
  * `file`: A `PATH` value pointing to the file where the warning or error originated.
  * `line`: The error/warning's line number.
  * `column`: The error/warning's line column.
  * `message`: An explanation of the warning/error.

#### Example

Executing `vyper-json path/to/contract1.vy path/to/other.vy`

should output something like:

```js
{
  "/absolute/path/to/contract1.vy": {
    "files": ["/absolute/path/to/contract1.vy", "/absolute/path/to/interface.vy"],
    "errors": [
      {
        "file": "/absolute/path/to/contract1.vy",
        "line": 1,
        "column": 20,
        "message": "A fatal error"
      }
    ],
    "warnings": [],
    "output": null
  },
  "/absolute/path/to/other.vy": {
    "files": ["/absolute/path/to/other.vy", "/path/path/to/ERC20.vy"],
    "errors": [],
    "warnings": [
      {
        "file": "/absolute/path/to/other.vy",
        "line": 2,
        "column": 30,
        "message": "A warning"
      }
    ],
    "output": { /* same as combined_json */ }
  }
}
```

## Backwards Compatibility

This VIP proposes the introduction of a new command-line tool, which should have no impact on the existing one. 

## Dependencies

This VIP has no dependencies.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/)

### PR DESCRIPTION
**Pull request by iamdefinitelyahuman**
### What I did
Added `vyper-json` CLI tool - closes #1520

### How I did it
See the [updated documentation](https://github.com/iamdefinitelyahuman/vyper/blob/13db68acfbee9084c4e4664bdff868117fcbc302/docs/compiling-a-contract.rst) for a detailed explanation of how `vyper-json` works.

Other changes in this PR:
* `vyper/compiler.py`: `compile_codes` accepts a dict of lists for `output_formats`, for specifying different outputs for each contract. Added annotations to make this clearer when reading the code.
* `vyper/compiler.py`: Added `source_id` arg to various functions, to allow different IDs when compiling multiple contracts
* `vyper/compile_lll.py`: modified `assembly_to_evm` to allow source maps from constructor bytecode
* `vyper/cli/vyper_compile.py`: Renamed variables in to be more verbose / consistent with `vyper_json`
* `vyper/cli/*.py`:  Refactored `_parse_cli_args` to simplify `argparse` testing

### How to verify it
Run the tests at `tests/cli/vyper_json`

### Description for the changelog
Added `vyper-json` CLI tool

### Cute Animal Picture
image

### CODE REVIEW

**Comment by fubuloubu** [comment]
Big, exciting change!

Let's ensure we get good review on this one, both from Vyper devs (2-3 of us) as well as some various toolmakers who might be impacted from this change (or otherwise take advantage of it).

CCing a few people I think might find this interesting here:
@mtbitcoin - etherscan
@montyly - slither (Crytic)
@b-mueller - MythX
@gnidan - truffle

**Comment by montyly** [comment]
@fubuloubu thanks for letting us know! It looks good, and it should be simple to integrate the format on our side.

As a small comment, it might be useful to add the compiler version to the json output. It will be easier for third-party tools to adjust in case of changes in the json format in the future.

**Comment by iamdefinitelyahuman** [comment]
@montyly good call! I actually already included that in the JSON output under the `compiler` field but forgot to document or test it.  Will push another commit shortly.

**Comment by alcuadrado** [comment]
Thanks for implementing this @iamdefinitelyahuman 🙌🏻

**Comment by fubuloubu** [comment]
@alcuadrado let us know if you have any issues using this in the gitter!

**Pull request merged**
