### PR TITLE
Fixed dropped units in convert

### LINKED ISSUE #865: Convert units should carry
### What's your issue about?

As @djrtwo found.

`convert` should preserve the unit that have been set, currently it doesn't:

```
b: uint256(meter) = 1234
a: int128 = convert(b, "int128") # should error
a: int128(meter) = convert(b, "int128") # should work
```

### How can it be fixed?

Fill this in if you know how to fix it.

### PR DESCRIPTION
**Pull request by ben-kaufman**
### - What I did
Fixed #865 

### - How I did it
Modified the convert function.

### - How to verify it
Check the test.

### - Cute Animal Picture

image

### CODE REVIEW

**Comment by jacqueswww** [comment]
I only saw your PR now, after mine was submitted.

I am probably going with mine because it fixes the convert in both directions `uint256 <-> int128`.

**Comment by ben-kaufman** [comment]
I am pretty sure that mine fixed both directions as well but that's fine.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacqueswww** [comment]
Ah I meant test😶 really sorry.

**Comment by ben-kaufman** [comment]
No problem, so should I close this one?

**Comment by jacqueswww** [comment]
Yes please ;)

**Pull request closed without merging**
