### PR TITLE
Update/fix coverage reporting config

### PR DESCRIPTION
**Pull request by davesque**
### What I did

Updated config for coverage reporting to coveralls.

### How I did it

Added appropriate requirements to test extras.  Updated `tox.ini` to run coverage upload wrapper script.  Added appropriate env var to circle CI project environment (this isn't reflected in PR changes).

### How to verify it

Trigger a circle CI build.

### Cute Animal Picture

Put a link to a cute animal picture inside the parenthesis-->

### CODE REVIEW

**Comment by fubuloubu** [comment]
This doesn't turn negative coverage into a blocker for merging, right?

In the past, we've only explored coverage misses at major checkpoints.

**Comment by davesque** [comment]
@fubuloubu I guess I'm not sure.  That would happen if the `coveralls` binary returned non-zero status for coverage under a certain level.  I'll check if that happens.

**Comment by davesque** [comment]
@fubuloubu I don't think that happens.  However, I've now got to figure out why Circle CI is ignoring my project env var setting.

**Comment by davesque** [comment]
Seems like the env var issue has to do with my lacking permissions for our circle CI account.  I'm going to try and work with our devops guys who manage the account to confirm whether or not this is the case.

Once I get that worked out, I believe this config should get us back up and running with coverage.  The one other issue that might pop up is that the coveralls utility might not merge coverage data from parallel test workers properly.  It claims to handle that but I thought I saw it misreporting it earlier when I was doing some manual testing.

**Comment by davesque** [comment]
I'm in touch with Circle CI support to try and get this worked out.  This issue shouldn't be happening and it feels like it's a problem on their end.

**Comment by davesque** [comment]
As it turns out, there is a setting on circle CI that controls whether or not build environment variables are set for builds from PR forks.  I didn't notice that but it totally makes sense why it's there.  Otherwise, by simply creating a PR, someone could retrieve those values by including malicious code in a PR, whether or not it gets merged.

I think this PR should be good to merge.  It just means that we'll only get coverage reporting on the master branch which is what we want anyway.

**Pull request merged**
